name = "QuantumESPRESSORecipes"
uuid = "268bcd87-39bf-4275-b2c8-49db87d88a9e"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
